// <auto-generated />
using System;
using System.Collections.Generic;
using GeoChangeRisk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoChangeRisk.Data.Migrations
{
    [DbContext(typeof(GeoChangeDbContext))]
    [Migration("20260206003513_AddAoiCloudCoverAndLastChecked")]
    partial class AddAoiCloudCoverAndLastChecked
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoChangeRisk.Data.Models.AreaOfInterest", b =>
                {
                    b.Property<string>("AoiId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Polygon>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<Point>("CenterPoint")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DefaultLookbackDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxCloudCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(20.0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ProcessingEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProcessingSchedule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AoiId");

                    b.HasIndex("BoundingBox");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundingBox"), "gist");

                    b.ToTable("AreasOfInterest", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AoiId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Criticality")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Dictionary<string, object>>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceDataset")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("AoiId");

                    b.HasIndex("AssetType");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("AoiId", "AssetType");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.ChangePolygon", b =>
                {
                    b.Property<Guid>("ChangePolygonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("AreaSqMeters")
                        .HasColumnType("double precision");

                    b.Property<int>("ChangeType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DetectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<double?>("MlConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("MlModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("NdviDropMax")
                        .HasColumnType("double precision");

                    b.Property<double>("NdviDropMean")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<double?>("SlopeDegreeMean")
                        .HasColumnType("double precision");

                    b.HasKey("ChangePolygonId");

                    b.HasIndex("ChangeType");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("RunId");

                    b.ToTable("ChangePolygons", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.ProcessingRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AfterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AfterSceneId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AoiId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("BeforeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BeforeSceneId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RunId");

                    b.HasIndex("AoiId");

                    b.HasIndex("Status");

                    b.HasIndex("AoiId", "Status");

                    b.ToTable("ProcessingRuns", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.RiskEvent", b =>
                {
                    b.Property<Guid>("RiskEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ChangePolygonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DismissedBy")
                        .HasColumnType("text");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("ScoringFactors")
                        .HasColumnType("jsonb");

                    b.HasKey("RiskEventId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ChangePolygonId");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("RiskScore");

                    b.HasIndex("AssetId", "RiskLevel");

                    b.ToTable("RiskEvents", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.Asset", b =>
                {
                    b.HasOne("GeoChangeRisk.Data.Models.AreaOfInterest", "AreaOfInterest")
                        .WithMany("Assets")
                        .HasForeignKey("AoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfInterest");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.ChangePolygon", b =>
                {
                    b.HasOne("GeoChangeRisk.Data.Models.ProcessingRun", "ProcessingRun")
                        .WithMany("ChangePolygons")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessingRun");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.ProcessingRun", b =>
                {
                    b.HasOne("GeoChangeRisk.Data.Models.AreaOfInterest", "AreaOfInterest")
                        .WithMany("ProcessingRuns")
                        .HasForeignKey("AoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfInterest");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.RiskEvent", b =>
                {
                    b.HasOne("GeoChangeRisk.Data.Models.Asset", "Asset")
                        .WithMany("RiskEvents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoChangeRisk.Data.Models.ChangePolygon", "ChangePolygon")
                        .WithMany("RiskEvents")
                        .HasForeignKey("ChangePolygonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("ChangePolygon");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.AreaOfInterest", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ProcessingRuns");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.Asset", b =>
                {
                    b.Navigation("RiskEvents");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.ChangePolygon", b =>
                {
                    b.Navigation("RiskEvents");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.ProcessingRun", b =>
                {
                    b.Navigation("ChangePolygons");
                });
#pragma warning restore 612, 618
        }
    }
}
