// <auto-generated />
using System;
using System.Collections.Generic;
using GeoChangeRisk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoChangeRisk.Data.Migrations
{
    [DbContext(typeof(GeoChangeDbContext))]
    [Migration("20260124151909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoChangeRisk.Data.Models.AreaOfInterest", b =>
                {
                    b.Property<string>("AoiId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Polygon>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<Point>("CenterPoint")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AoiId");

                    b.HasIndex("BoundingBox");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundingBox"), "gist");

                    b.ToTable("AreasOfInterest", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AoiId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Criticality")
                        .HasColumnType("integer");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Dictionary<string, object>>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceDataset")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceFeatureId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssetId");

                    b.HasIndex("AoiId");

                    b.HasIndex("AssetType");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("AoiId", "AssetType");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.Asset", b =>
                {
                    b.HasOne("GeoChangeRisk.Data.Models.AreaOfInterest", "AreaOfInterest")
                        .WithMany("Assets")
                        .HasForeignKey("AoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaOfInterest");
                });

            modelBuilder.Entity("GeoChangeRisk.Data.Models.AreaOfInterest", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
