using NetTopologySuite.Geometries;

namespace GeoChangeRisk.Data.Models;

/// <summary>
/// Represents a detected land-surface change polygon from satellite imagery analysis.
/// Generated by the raster pipeline when significant NDVI changes are detected.
/// </summary>
public class ChangePolygon
{
    /// <summary>
    /// Unique identifier for the change polygon.
    /// </summary>
    public Guid ChangePolygonId { get; set; }

    /// <summary>
    /// Foreign key to the processing run that generated this polygon.
    /// </summary>
    public Guid RunId { get; set; }

    /// <summary>
    /// Spatial geometry of the detected change area.
    /// Stored as a PostGIS polygon (SRID 4326 - WGS84).
    /// </summary>
    public required Polygon Geometry { get; set; }

    /// <summary>
    /// Area of the change polygon in square meters.
    /// </summary>
    public double AreaSqMeters { get; set; }

    /// <summary>
    /// Mean NDVI drop within the polygon (negative indicates vegetation loss).
    /// </summary>
    public double NdviDropMean { get; set; }

    /// <summary>
    /// Maximum NDVI drop within the polygon.
    /// </summary>
    public double NdviDropMax { get; set; }

    /// <summary>
    /// Classification of the change type.
    /// </summary>
    public ChangeType ChangeType { get; set; } = ChangeType.Unknown;

    /// <summary>
    /// Mean slope in degrees within the polygon (from DEM analysis).
    /// </summary>
    public double? SlopeDegreeMean { get; set; }

    /// <summary>
    /// Timestamp when the change was detected.
    /// </summary>
    public DateTime DetectedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// ML model confidence score (0-1) if change type was ML-classified.
    /// </summary>
    public double? MlConfidence { get; set; }

    /// <summary>
    /// Version identifier of the ML model used for classification.
    /// </summary>
    public string? MlModelVersion { get; set; }

    /// <summary>
    /// Navigation property to the parent processing run.
    /// </summary>
    public ProcessingRun? ProcessingRun { get; set; }

    /// <summary>
    /// Navigation property for risk events associated with this change polygon.
    /// </summary>
    public ICollection<RiskEvent> RiskEvents { get; set; } = new List<RiskEvent>();
}
